#! vi: set filetype=ansible:
---
- hosts: zabbix_master
  sudo: true
  user: vagrant
  tasks:
    - name: use mirror server
      replace:
        dest=/etc/apt/sources.list
        regexp='http:\/\/[^/]+\/ubuntu'
        replace='http://ftp.riken.jp/Linux/ubuntu'
        backup=yes

    #
    # add zabbix repository
    #
    - apt_key:
        url=http://repo.zabbix.com/zabbix-official-repo.key
        state=present
    - apt_repository:
        repo={{ item }}
        state=present 
      with_items:
        - 'deb http://repo.zabbix.com/zabbix/3.0/ubuntu trusty main'
        - 'deb-src http://repo.zabbix.com/zabbix/3.0/ubuntu trusty main'

    #
    # install zabbix packages
    #
    - apt:
        name={{ item }}
        state=present
      with_items:
        - 'gzip'
        - 'zabbix-server-pgsql'
        - 'zabbix-frontend-php'
        - 'python-psycopg2'
        - 'php5-pgsql'


    # php.ini for zabbix
    - replace:
        dest=/etc/php5/apache2/php.ini
        regexp='^;(date\.timezone.*=).*'
        replace='\1 Asia/Tokyo'
        backup=yes

    - template:
        src=/templates/etc/zabbix/zabbix_server.conf.j2
        dest=/etc/zabbix/zabbix_server.conf
        owner=root
        group=root
        mode=0644
        backup=yes

    #
    # initialized DB for zabbix
    #
    - postgresql_user:
        name=zabbix
        password=6117982f58a0b71e
      sudo: yes
      sudo_user: postgres

    - postgresql_db:
        name=zabbix owner=zabbix state=present
      sudo: yes
      sudo_user: postgres

    - shell: |
        if ! (psql -c '\l' | grep -q zabbix) ; then
          /bin/zcat /usr/share/doc/zabbix-server-pgsql/create.sql.gz > /tmp/initialized-zabbix.sql && \
          psql zabbix < /tmp/initialized-zabbix.sql && \
          rm -v /tmp/initialized-zabbix.sql
        fi
      sudo: yes
      sudo_user: postgres
