---
- name: use mirror server
  replace:
    dest=/etc/apt/sources.list
    regexp='http:\/\/[^/]+\/ubuntu'
    replace='http://ftp.riken.jp/Linux/ubuntu'
    backup=yes

- apt:
    name={{ item }}
    state=latest
    update_cache=yes
  with_items:
    - gzip
    - bash-completion

- name: timezone update
  copy:
    content='Asia/Tokyo'
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    - update timezone

- locale_gen:
    name=ja_JP.UTF-8
    state=present
