#! vi: set filetype=ansible:
---
- apt_key:
    url=http://repo.zabbix.com/zabbix-official-repo.key
    state=present
- apt_repository:
    repo={{ item }}
    state=present 
  with_items:
    - 'deb http://repo.zabbix.com/zabbix/3.0/ubuntu trusty main'
    - 'deb-src http://repo.zabbix.com/zabbix/3.0/ubuntu trusty main'

- apt:
    name={{ item }}
    state=present
  with_items:
    - 'zabbix-server-pgsql'
    - 'zabbix-frontend-php'
    - 'zabbix-get'
    - 'python-psycopg2'
    - 'php5-pgsql'
    - 'fonts-ipaexfont'

#
# Japanes font for zabbix metrics
#
- alternatives:
    name=zabbix-frontend-font
    path=/usr/share/fonts/opentype/ipaexfont-gothic/ipaexg.ttf

#
# initialize database
#
- name: change Auth method
  replace:
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    regexp='^(local\s+all\s+all\s+)peer'
    replace='\1md5'
    backup=yes
    owner=postgres
    group=postgres
    mode=0640
  register: pg_auth_update_check

- name: reload postgresql
  service:
    name=postgresql
    state=reloaded
  when: pg_auth_update_check.changed

- postgresql_user:
    name=zabbix
    password=6117982f58a0b71e
  become: yes
  become_user: postgres

- postgresql_db:
    name=zabbix owner=zabbix state=present
  become: yes
  become_user: postgres

- stat:
    path=/etc/zabbix/.create.sql.done
  register: create_db_sym

- shell: |
    gunzip -c /usr/share/doc/zabbix-server-pgsql/create.sql.gz | psql -U zabbix zabbix
  register: db_initialized_check
  environment:
    PGPASSWORD: 6117982f58a0b71e
  become: yes
  become_user: postgres
  when: create_db_sym.stat.exists == False

- file:
    path=/etc/zabbix/.create.sql.done
    state=touch
    owner=root
    group=root
    mode=644
  when: db_initialized_check.changed

#
# zabbix_server agent
# 
- template:
    src=etc/zabbix/zabbix_server.conf.j2
    dest=/etc/zabbix/zabbix_server.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    - zabbix-server reloaded


#
# Web server config
#
- template:
    src=etc/zabbix/web/zabbix.conf.php.j2
    dest=/etc/zabbix/web/zabbix.conf.php
    owner=www-data
    group=www-data
    mode=0644

- replace:
    dest=/etc/php5/apache2/php.ini
    regexp='^;(date\.timezone.*=).*'
    replace='\1 Asia/Tokyo'
    backup=yes
  notify:
    - apache2 reloaded
