- apt_key:
    url=http://repo.zabbix.com/zabbix-official-repo.key
    state=present
- apt_repository:
    repo={{ item }}
    state=present 
  with_items:
    - 'deb http://repo.zabbix.com/zabbix/3.0/ubuntu trusty main'
    - 'deb-src http://repo.zabbix.com/zabbix/3.0/ubuntu trusty main'

- apt:
    name={{ item }}
    state=present
  with_items:
    - 'zabbix-server-pgsql'
    - 'zabbix-frontend-php'
    - 'zabbix-get'
    - 'python-psycopg2'
    - 'php5-pgsql'
    - 'fonts-ipaexfont'
